language: generic
sudo: required
services:
    - docker

before-install: 
    - docker build -t defish1962/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true defish1962/docker-react npm run test